"""add delete_flag column to submissions

Revision ID: a26523696faa
Revises: c1640fe3d755
Create Date: 2026-10-03 12:09:38.255981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26523696faa'
down_revision: Union[str, Sequence[str], None] = 'c1640fe3d755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('delete_flag', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'delete_flag')
    # ### end Alembic commands ###
